// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ3aCARVoruhsNrMvmAo0cAzPHKeKE1jI',
    appId: '1:361301911909:web:a5f4ffe55111f9d5c9198c',
    messagingSenderId: '361301911909',
    projectId: 'expense-tracker-codeclau-40ad4',
    authDomain: 'expense-tracker-codeclau-40ad4.firebaseapp.com',
    storageBucket: 'expense-tracker-codeclau-40ad4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Gqjq0CYy-Jg1SopTgk_l3-Cc6HdBwOc',
    appId: '1:361301911909:android:faacb981d3dfe802c9198c',
    messagingSenderId: '361301911909',
    projectId: 'expense-tracker-codeclau-40ad4',
    storageBucket: 'expense-tracker-codeclau-40ad4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADJ8UuPE47SNC-yVMfNyB8RzwP1FVzgRc',
    appId: '1:361301911909:ios:14908eaee85a59acc9198c',
    messagingSenderId: '361301911909',
    projectId: 'expense-tracker-codeclau-40ad4',
    storageBucket: 'expense-tracker-codeclau-40ad4.appspot.com',
    iosClientId: '361301911909-1lv1rqvcub2sorsip4kjjcv4hesp1sbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADJ8UuPE47SNC-yVMfNyB8RzwP1FVzgRc',
    appId: '1:361301911909:ios:9582387a044b170dc9198c',
    messagingSenderId: '361301911909',
    projectId: 'expense-tracker-codeclau-40ad4',
    storageBucket: 'expense-tracker-codeclau-40ad4.appspot.com',
    iosClientId: '361301911909-aa69eb56u5c78m3sfuu48o3am433hpsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
